version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:jnjnuh@mysql/amazon_bookstore
      - flipkart_DATABASE_URL=mysql+pymysql://root:jnjnuh@mysql/flipkart_bookstore
      - sapna_DATABASE_URL=mysql+pymysql://root:jnjnuh@mysql/sapna_bookstore
    volumes:
      - .:/app
    command: python -m app.main

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=jnjnuh
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pjnjnuh"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
